### ISSUE TITLE
vmprof 0.4.12 fails to compile with Python 3.6 under Windows 64 bit

### ISSUE THREAD

**Issue by divenex** [vmprof/vmprof-python#177]
`vmprof` still has compilation issues under Windows 10 64 bit (also see #121).

Given the persistent install difficulties, and the GigaBytes of space required for BuildTools installation, it would be great if `vmprof` wheels were made available for Windows too!

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\user\Miniconda3\include -IC:\Users\user\Miniconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\include" /Tcsrc/_vmprof.c /Fobuild\temp.win-amd64-3.6\Release\src/_vmprof.obj -DVMPROF_WINDOWS=1 "-I src/" "-I src/libbacktrace"
    _vmprof.c
    c:\users\user\miniconda3\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.14.26428\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```

**Comment by mattip** [comment]
Wheels are available. Closing.
